import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/plugins/font-awesome/all.min.css" />
      </Head>
      <body>
        <Main />
        <NextScript />
        {/* import bootstrap js on plugins folder */}
        <script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="/plugins/font-awesome/all.min.js"></script>
      </body>
    </Html>
  )
}
